DB:
    # prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.160.20.65\SSQL_2016;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!};
    # New prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.9.10.59\SQLVP201606;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!};
    # Local conn string: Driver={ODBC Driver 17 for SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!}
    # DB connection string
    mdb_conn_str: Driver={ODBC Driver 17 for SQL Server};Server={!server!};Database={!db_name!};UID={!db_user_name!};PWD={!db_user_pwd!};
    db_plh_server: "{!server!}"
    db_plh_db_name: "{!db_name!}"
    db_plh_user_name: "{!db_user_name!}"
    db_plh_user_pwd: "{!db_user_pwd!}"
    env_db_server: ST_DB_SERVER
    env_db_name: ST_DB_NAME
    env_db_user_name: ST_DB_USER_NAME
    env_db_user_pwd: ST_DB_USER_PWD

    # sql calls views
    sql_view_metadata_stats: select * from vw_get_metadata_study_stats
    sql_view_aliquot_data_stats: select * from vw_get_aliquot_dataset_stats

    # sql call for metadata dataset
    sql_sp_metadata: exec usp_get_metadata
    # sql call for sample info (manifest id based) dataset
    sql_sp_sampleinfo_dataset: usp_get_aliquot_dataset

    # sql calls to get contents for report filters
    sql_get_programs: exec dbo.usp_get_programs_for_filters
    sql_get_centers: exec dbo.usp_get_centers_for_filters
    sql_get_studies: exec dbo.usp_get_studies_for_filters
    sql_get_dataset_types: exec dbo.usp_get_aliquot_dataset_types_for_filters

    # sql parameters
    param_study_id: "@study_id = {study_id}"
    param_center_id: "@center_id = {center_id}"
    param_center_ids: "@center_ids = '{center_ids}'"
    param_sample_ids: "@sample_ids = '{sample_ids}'"
    param_sample_delim: "@sample_delim = '{sample_delim}'"
    param_aliquot_ids: "@aliquot_ids = '{aliquot_ids}'"
    param_aliquot_delim: "@aliquot_delim = '{aliquot_delim}'"
    param_aliquot_id_contains: "@aliquot_id_contains = '{aliquot_id_contains}'"
    param_dataset_type_id: "@dataset_type_id = {dataset_type_id}"

Location:

    #name of the folder where all logs files will be stored
    log_folder_name: logs

Logging:
    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    custom_logging: True # Expected value True/False. If set to False, no logging will be performed
    main_log_level: INFO  # DEBUG
    keep_log_days: 60 # number of days to keep log files
    clean_log_frequency_days: 7 # how often the log cleaner runs (in days)

Email:
    #default settings for sending emails
    smtp_server: {smtp_server} #smtp.mssm.edu
    env_smtp: ST_SMTP_SERVER
    smtp_server_port: 25
    default_from_email: stas.rirak@mssm.edu
    send_to_emails: ['stasrirak.ms@gmail.com','stas.rirak@mssm.edu']
    send_emails: True # expected values: True, False

    # name of the application to be reported in the email notifications
    env_name: ST_ENV_NAME
    application_id: SealfonLab SampleInfo API - {env_name} server

Validate:
    # list of environment variable required to be set for a current user in order to run the application
    environment_variables:
        default: # default list of variables required for all runs
            - ST_DB_SERVER
            - ST_DB_NAME
            - ST_DB_USER_NAME
            - ST_DB_USER_PWD
            - ST_SMTP_SERVER
            - ST_ENV_NAME
